USER_NAME := djcastaldo
USER_PATH := users/$(USER_NAME)
include $(USER_PATH)/rules.mk
CONSOLE_ENABLE = no
KEYBOARD_SHARED_EP = no
FACTORY_TEST_FNJZ_ENABLE = no
LTO_ENABLE = no 
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
KEY_LOCK_ENABLE = yes
LEADER_ENABLE = yes
EXTRAFLAGS += -DKEYBOARD_IS_LEMOKEY
ifeq ($(strip $(FACTORY_TEST_FNJZ_ENABLE)), yes)
    OPT_DEFS += -DFACTORY_TEST_FNJZ_ENABLE
endif
