USER_PATH := users/djcastaldo
include users/djcastaldo/rules.mk
CONSOLE_ENBALE = no 
KEYBOARD_SHARED_EP = yes
EXTRAKEY_ENABLE = yes 
MOUSEKEY_ENBALE = yes 
DEFERRED_EXEC_ENABLE = yes 
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes 
DYNAMIC_MACRO_ENABLE = yes 
KEY_LOCK_ENABLE = yes
LEADER_ENABLE = yes
EXTRAFLAGS += -DKEYBOARD_IS_KEYCHRON
