/* Copyright 2022~2024 @ Keychron (https://www.lemokey.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "stdint.h"

// clang-format off
enum {
    KC_TASK_VIEW = QK_KB_0,
    KC_FILE_EXPLORER,
    KC_LOCK_SCREEN,        // Lock screen
    KC_MCTRL,
    KC_LNPAD,
    KC_LOPTN,
    KC_ROPTN,
    KC_LCMMD,
    KC_RCMMD,
#ifdef LK_WIRELESS_ENABLE
    BT_HST1,
    BT_HST2,
    BT_HST3,
    P2P4G,
    BAT_LVL,
    __LK_WIRELESS_ENABLE_END = BAT_LVL,
#else
    BT_HST1 = _______,
    BT_HST2 = _______,
    BT_HST3 = _______,
    P2P4G   = _______,
    BAT_LVL = _______,
    __LK_WIRELESS_ENABLE_END = KC_LOCK_SCREEN,
#endif
    SECRET0,
    SECRET1,
    SECRET2,
    SECRET3,
    SECRET4,
    SECRET5,
    SECRET6,
    SECRET7,
    SECRET8,
    SECRET9,
    SECRET10,
    SECRET11,
    SECRET12,
    SECRET13,
    SECRET14,
    SECRET15,
    SECRET16,
    SECRET17,
    SECRET18,
    SECRET19,
    SECRET20,
    SECRET21,
    SECRET22,
    SECRET23,
    SECRET24,
    SECRET25,
    SECRET26,
    SECRET27,
    SECRET28,
    SECRET29,
    SECRET30,
    SECRET31,
    JIGGLE,
    FJLIGHT,
    HROWLIGHT,
    KTRACK,
    WAVE,
    ARROW,
    BSPCFAST,
    TMUXLKEY,
    TMUXLCMD,
    TMONON,
    TMONOF,
    TVISON,
    TVISOF,
    TWINLFT,
    TWINRGT,
    TJPANE,
    ENC_TMON,
    DUAL_PLUSMIN,
    DUAL_MULTDIV,
    VI_REPLACE,
    GIT_ADD,
    GIT_COMMIT,
    GIT_PUSH,
    GIT_CHKOUT,
    GIT_LOG,
    LTRANS,
    STHRU,
    UNDERLN,
    BARTEXT,
    BBRTEXT,
    MK_HOLD,
    MK_ACCEL0,
    MK_ACCEL2,
    COLORTEST,
    OPT2,
    OPT3,
    OPT4,
    OPT5,
    OPT6,
    OPT7,
    OPT8,
    OPT9,
    OPT0,
    OPTMIN,
    OPTEQ,
    OPTQ,
    OPTW,
    OPTR,
    OPTT,
    OPTY,
    OPTO,
    OPTP,
    OPTLBR,
    OPTRBR,
    OPTBSL,
    OPTA,
    OPTS,
    OPTD,
    OPTF,
    OPTG,
    OPTH,
    OPTJ,
    OPTK,
    OPTL,
    OPTSEM,
    OPTAPO,
    OPTZ,
    OPTX,
    OPTC,
    OPTV,
    OPTB,
    OPTM,
    OPTCOM,
    OPTDOT,
    OPTSLS,
    SUITH,
    SUITD,
    SUITC,
    SUITS,
    SUP1,
    SUP2,
    SUP3,
    NBSP,
    CIRCL1,
    CIRCL2,
    CIRCL3,
    CIRCL4,
    CIRCL5,
    CIRCL6,
    CIRCL7,
    CIRCL8,
    CIRCL9,
    CIRCL0,
    CIRCLQ,
    CIRCLW,
    CIRCLE,
    CIRCLR,
    CIRCLT,
    CIRCLY,
    CIRCLU,
    CIRCLI,
    CIRCLO,
    CIRCLP,
    CIRCLA,
    CIRCLS,
    CIRCLD,
    CIRCLF,
    CIRCLG,
    CIRCLH,
    CIRCLJ,
    CIRCLK,
    CIRCLL,
    CIRCLZ,
    CIRCLX,
    CIRCLC,
    CIRCLV,
    CIRCLB,
    CIRCLN,
    CIRCLM,
    E_SMILE,
    E_SMIRK,
    E_ASTON,
    E_SAD,
    E_CAR,
    E_BUS,
    E_TRAIN,
    E_TAXI,
    E_FLAGUS,
    E_FLAGPI,
    E_GLOBE,
    E_PIZZA,
    E_BURGER,
    E_CHICKEN,
    E_TACO,
    E_SNAIL,
    E_NINJA,
    E_STOP,
    E_HAND,
    E_SHH,
    E_PACKAGE,
    E_POINTU,
    E_POINTD,
    E_POINTL,
    E_POINTR,
    E_DRINK,
    E_EMARK,
    E_QMARK,
    E_CMARK,
    E_BULB,
    E_SSHOT,
    E_MIC,
    E_TRASH,
    E_I,
    E_K0,
    E_K1,
    E_K2,
    E_K3,
    E_K4,
    E_K5,
    E_K6,
    E_K7,
    E_K8,
    E_K9,
    E_STAR,
    E_HASH,
    E_MINS,
    E_PLUS,
    E_DIV,
    E_GRIM,
    E_KB,
    E_OK,
    E_SGLASS,
    E_BOTTLE,
    FLASH_KB,
    BOOTLDR,
    NEW_SAFE_RANGE,
};

#define KC_TASK KC_TASK_VIEW
#define KC_FILE KC_FILE_EXPLORER
#define KC_LOCK KC_LOCK_SCREEN

typedef struct PACKED {
    uint8_t len;
    uint8_t keycode[2];
} key_combination_t;

bool process_record_lemokey_common(uint16_t keycode, keyrecord_t *record);
void lemokey_common_task(void);

#ifdef ENCODER_ENABLE
void encoder_cb_init(void);
#endif

